### ISSUE TITLE
[FEAT] Tab3 - 미들파이 뷰 구현

### ISSUE THREAD

**Issue by seunggyun-jeong** [seunggyun-jeong/MC2-Team7-Fighring#1]
## 📌  Feature Issue
리빈이가 만든 미들파이 보고 뷰 구현 할거에요

## 📝  To-do
- [x] 나의 유형 결과지
- [x] 36일 전 잠금 화면
- [x] 다른 유형 보기
- [x] 테스트 메인 화면
- [x] 테스트 화면
