### ISSUE TITLE
[FIX] 로고, 온보딩, 런치스크린 이미지 수정

### ISSUE THREAD

**Issue by seunggyun-jeong** [seunggyun-jeong/MC2-Team7-Fighring#113]
## 📌  Feature Issue
로고, 온보딩, 런치스크린 이미지 수정

## 📝  To-do
- [x] 로고 이미지 수정
- [x] 온보딩 이미지 수정
- [x] 런치 스크린 이미지 수정
