### ISSUE TITLE
[FIX] Tab3-TinyIssue

### ISSUE THREAD

**Issue by seunggyun-jeong** [seunggyun-jeong/MC2-Team7-Fighring#140]
## 📌  Feature Issue
User Testing을 통해 얻은 피드백을 기반으로 수정할 예정입니다.

## 📝  To-do
- [x] 다른 유형보기에 유형 이름 추가
- [x] 플립 카드 기능 설명 추가
- [x] 앱을 초기화해야 버튼 활성화됨 (AllClear)
